---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
language: en
ignorePaths:
  - node_modules
  - dist
dictionaries:
  - en_US
  - en-gb
  - companies
  - softwareTerms
  - misc
  - typescript
  - node
  - html
  - css
  - bash
  - fonts
  - filetypes
  - npm
words:
  - ScarletFlash
  - Fedor
  - Usakov
  - autofix
  - ESBuild
